version: '3'
services:
  db:
    image: mongo:4
    command: mongod --oplogSize 128
    volumes:
      - ./data/db:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: ROOT

  mongo:
    image: mongo-express
    labels:
      - traefik.docker.network=traefik
      - traefik.http.routers.${APP_NAME}-db.rule=Host("${APP_NAME}-db.${APP_DOMAIN}")
      - traefik.http.routers.${APP_NAME}-db.tls=true
      - traefik.http.services.${APP_NAME}-db.loadbalancer.server.port=8081
    networks:
      - traefik
      - default
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: ROOT
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ROOT
    depends_on:
      - db

  app:
    build: ./
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      MONGO_URL: mongodb://db:27017/
      # MONGO_URL: mongodb://root:ROOT@db:27017/
    networks:
      - traefik
      - default
    labels:
      - traefik.docker.network=traefik
      - traefik.http.routers.${APP_NAME}.rule=Host("${APP_NAME}.${APP_DOMAIN}")
      - traefik.http.routers.${APP_NAME}.tls=true
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https
    depends_on:
      - db

networks:
  traefik:
    external: true
